permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# author
author: 
  name: Lillian Cheng
  email: lillian.cheng2012@gmail.com
  link: 
  weibo: 
  github: http://github.com/lilliancheng2012
  music: 
  linkedin: 

# website
title: Lillian's Blog
description: My personal blog
url: 
rss_url: /pages/atom.xml

# gavatar
gavatar: /public/img/deer3.png
favicon: /public/img/deer3.png

# google analytics
ga:
  id: UA-54262064-1 
  url: 

# disqus
disqus:
  shortname: 

# active page
active: Demo

# category
cates: 
  - Optimization
  - LaTeX

# Tags
locals:
  tags: Tags
  about: About
  newest: Latest
  archive: Archive
